version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: test-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 198920
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: portfolio-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: portfolio_db
      DB_USER: postgres
      DB_PASSWORD: 198920
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npx nodemon --exec "npx ts-node" src/index.ts

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: portfolio-client
    depends_on:
      - api
    restart: always
    working_dir: /app
    volumes:
      - ./client:/app
      - notused:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHMAN_USE_POLLING=true
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_USE_DEV_SERVER=true
      - FAST_REFRESH=true
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    # command: ["npx", "expo", "start", "--tunnel", "-c"]

volumes:
  pgdata:
  notused:
